export const PERMISSION_CATALOG = [
  // platform
  { code: 'platform:tenant:view',         module: 'platform', resource: 'tenant',        action: 'view',    description: 'View all tenants' },
  { code: 'platform:tenant:create',       module: 'platform', resource: 'tenant',        action: 'create',  description: 'Provision new tenant' },
  { code: 'platform:tenant:suspend',      module: 'platform', resource: 'tenant',        action: 'suspend', description: 'Suspend a tenant' },
  { code: 'platform:plan:manage',         module: 'platform', resource: 'plan',          action: 'manage',  description: 'Manage subscription plans' },
  { code: 'platform:subscription:manage', module: 'platform', resource: 'subscription',  action: 'manage',  description: 'Manage tenant subscriptions' },
  // admin
  { code: 'admin:user:view',              module: 'admin', resource: 'user',         action: 'view',    description: 'View tenant users' },
  { code: 'admin:user:invite',            module: 'admin', resource: 'user',         action: 'invite',  description: 'Invite users to tenant' },
  { code: 'admin:user:suspend',           module: 'admin', resource: 'user',         action: 'suspend', description: 'Suspend a user' },
  { code: 'admin:role:view',              module: 'admin', resource: 'role',         action: 'view',    description: 'View roles' },
  { code: 'admin:role:create',            module: 'admin', resource: 'role',         action: 'create',  description: 'Create custom roles' },
  { code: 'admin:role:update',            module: 'admin', resource: 'role',         action: 'update',  description: 'Edit roles' },
  { code: 'admin:role:delete',            module: 'admin', resource: 'role',         action: 'delete',  description: 'Delete custom roles' },
  { code: 'admin:settings:view',          module: 'admin', resource: 'settings',     action: 'view',    description: 'View tenant settings' },
  { code: 'admin:settings:update',        module: 'admin', resource: 'settings',     action: 'update',  description: 'Update tenant settings' },
  { code: 'admin:audit_log:view',         module: 'admin', resource: 'audit_log',    action: 'view',    description: 'View audit log' },
  { code: 'admin:notification:manage',    module: 'admin', resource: 'notification', action: 'manage',  description: 'Manage notification settings' },
  // accounts
  { code: 'accounts:coa:view',            module: 'accounts', resource: 'coa',       action: 'view',    description: 'View chart of accounts' },
  { code: 'accounts:coa:create',          module: 'accounts', resource: 'coa',       action: 'create',  description: 'Create accounts' },
  { code: 'accounts:coa:update',          module: 'accounts', resource: 'coa',       action: 'update',  description: 'Edit accounts' },
  { code: 'accounts:coa:delete',          module: 'accounts', resource: 'coa',       action: 'delete',  description: 'Delete accounts' },
  { code: 'accounts:journal:view',        module: 'accounts', resource: 'journal',   action: 'view',    description: 'View journal entries' },
  { code: 'accounts:journal:create',      module: 'accounts', resource: 'journal',   action: 'create',  description: 'Post journal entries' },
  { code: 'accounts:journal:post',        module: 'accounts', resource: 'journal',   action: 'post',    description: 'Approve and post journals' },
  { code: 'accounts:period:view',         module: 'accounts', resource: 'period',    action: 'view',    description: 'View fiscal periods' },
  { code: 'accounts:period:manage',       module: 'accounts', resource: 'period',    action: 'manage',  description: 'Open/close periods' },
  { code: 'accounts:invoice:view',        module: 'accounts', resource: 'invoice',   action: 'view',    description: 'View invoices' },
  { code: 'accounts:invoice:create',      module: 'accounts', resource: 'invoice',   action: 'create',  description: 'Create invoices' },
  { code: 'accounts:invoice:update',      module: 'accounts', resource: 'invoice',   action: 'update',  description: 'Edit invoices' },
  { code: 'accounts:invoice:delete',      module: 'accounts', resource: 'invoice',   action: 'delete',  description: 'Delete draft invoices' },
  { code: 'accounts:invoice:approve',     module: 'accounts', resource: 'invoice',   action: 'approve', description: 'Approve invoices' },
  { code: 'accounts:bill:view',           module: 'accounts', resource: 'bill',      action: 'view',    description: 'View vendor bills' },
  { code: 'accounts:bill:create',         module: 'accounts', resource: 'bill',      action: 'create',  description: 'Create vendor bills' },
  { code: 'accounts:bill:update',         module: 'accounts', resource: 'bill',      action: 'update',  description: 'Edit vendor bills' },
  { code: 'accounts:bill:delete',         module: 'accounts', resource: 'bill',      action: 'delete',  description: 'Delete draft vendor bills' },
  { code: 'accounts:bill:post',           module: 'accounts', resource: 'bill',      action: 'post',    description: 'Post vendor bills to general ledger' },
  { code: 'accounts:payment:view',        module: 'accounts', resource: 'payment',   action: 'view',    description: 'View payments' },
  { code: 'accounts:payment:create',      module: 'accounts', resource: 'payment',   action: 'create',  description: 'Record payments' },
  { code: 'accounts:tax:view',            module: 'accounts', resource: 'tax',       action: 'view',    description: 'View tax rates' },
  { code: 'accounts:tax:manage',          module: 'accounts', resource: 'tax',       action: 'manage',  description: 'Manage tax rates' },
  { code: 'accounts:report:view',         module: 'accounts', resource: 'report',    action: 'view',    description: 'View financial reports' },
  { code: 'accounts:budget:create',       module: 'accounts', resource: 'budget',    action: 'create',  description: 'Create budgets' },
  { code: 'accounts:budget:update',       module: 'accounts', resource: 'budget',    action: 'update',  description: 'Edit budget lines and status' },
  { code: 'accounts:contact:view',        module: 'accounts', resource: 'contact',   action: 'view',    description: 'View contacts (vendors & customers)' },
  { code: 'accounts:contact:manage',      module: 'accounts', resource: 'contact',   action: 'manage',  description: 'Create and edit contacts' },
  // scm
  { code: 'scm:vendor:view',              module: 'scm', resource: 'vendor',      action: 'view',    description: 'View vendors' },
  { code: 'scm:vendor:create',            module: 'scm', resource: 'vendor',      action: 'create',  description: 'Create vendors' },
  { code: 'scm:vendor:update',            module: 'scm', resource: 'vendor',      action: 'update',  description: 'Edit vendors' },
  { code: 'scm:item:view',                module: 'scm', resource: 'item',        action: 'view',    description: 'View items/products' },
  { code: 'scm:item:create',              module: 'scm', resource: 'item',        action: 'create',  description: 'Create items' },
  { code: 'scm:item:update',              module: 'scm', resource: 'item',        action: 'update',  description: 'Edit items' },
  { code: 'scm:inventory:view',           module: 'scm', resource: 'inventory',   action: 'view',    description: 'View stock levels' },
  { code: 'scm:inventory:adjust',         module: 'scm', resource: 'inventory',   action: 'adjust',  description: 'Adjust stock' },
  { code: 'scm:transfer:create',          module: 'scm', resource: 'transfer',    action: 'create',  description: 'Create stock transfers' },
  { code: 'scm:po:view',                  module: 'scm', resource: 'po',          action: 'view',    description: 'View purchase orders' },
  { code: 'scm:po:create',               module: 'scm', resource: 'po',          action: 'create',  description: 'Create purchase orders' },
  { code: 'scm:po:update',               module: 'scm', resource: 'po',          action: 'update',  description: 'Edit purchase orders' },
  { code: 'scm:po:approve',              module: 'scm', resource: 'po',          action: 'approve', description: 'Approve purchase orders' },
  { code: 'scm:grn:view',                module: 'scm', resource: 'grn',         action: 'view',    description: 'View goods receipt notes' },
  { code: 'scm:grn:create',              module: 'scm', resource: 'grn',         action: 'create',  description: 'Create GRNs' },
  { code: 'scm:requisition:view',        module: 'scm', resource: 'requisition', action: 'view',    description: 'View requisitions' },
  { code: 'scm:requisition:create',      module: 'scm', resource: 'requisition', action: 'create',  description: 'Create requisitions' },
  { code: 'scm:requisition:approve',     module: 'scm', resource: 'requisition', action: 'approve', description: 'Approve requisitions' },
  // crm
  { code: 'crm:lead:view',               module: 'crm', resource: 'lead',        action: 'view',    description: 'View leads' },
  { code: 'crm:lead:create',             module: 'crm', resource: 'lead',        action: 'create',  description: 'Create leads' },
  { code: 'crm:lead:update',             module: 'crm', resource: 'lead',        action: 'update',  description: 'Edit leads' },
  { code: 'crm:lead:delete',             module: 'crm', resource: 'lead',        action: 'delete',  description: 'Delete leads' },
  { code: 'crm:contact:view',            module: 'crm', resource: 'contact',     action: 'view',    description: 'View contacts' },
  { code: 'crm:contact:create',          module: 'crm', resource: 'contact',     action: 'create',  description: 'Create contacts' },
  { code: 'crm:contact:update',          module: 'crm', resource: 'contact',     action: 'update',  description: 'Edit contacts' },
  { code: 'crm:opportunity:view',        module: 'crm', resource: 'opportunity', action: 'view',    description: 'View opportunities' },
  { code: 'crm:opportunity:create',      module: 'crm', resource: 'opportunity', action: 'create',  description: 'Create opportunities' },
  { code: 'crm:opportunity:update',      module: 'crm', resource: 'opportunity', action: 'update',  description: 'Edit opportunities' },
  { code: 'crm:quotation:view',          module: 'crm', resource: 'quotation',   action: 'view',    description: 'View quotations' },
  { code: 'crm:quotation:create',        module: 'crm', resource: 'quotation',   action: 'create',  description: 'Create quotations' },
  { code: 'crm:quotation:approve',       module: 'crm', resource: 'quotation',   action: 'approve', description: 'Approve quotations' },
  { code: 'crm:activity:view',           module: 'crm', resource: 'activity',    action: 'view',    description: 'View CRM activities' },
  { code: 'crm:activity:create',         module: 'crm', resource: 'activity',    action: 'create',  description: 'Log CRM activities' },
  // hrm
  { code: 'hrm:employee:view',           module: 'hrm', resource: 'employee',   action: 'view',    description: 'View employees' },
  { code: 'hrm:employee:create',         module: 'hrm', resource: 'employee',   action: 'create',  description: 'Add employees' },
  { code: 'hrm:employee:update',         module: 'hrm', resource: 'employee',   action: 'update',  description: 'Edit employee records' },
  { code: 'hrm:attendance:view',         module: 'hrm', resource: 'attendance', action: 'view',    description: 'View attendance records' },
  { code: 'hrm:attendance:manage',       module: 'hrm', resource: 'attendance', action: 'manage',  description: 'Manage attendance' },
  { code: 'hrm:leave:view',              module: 'hrm', resource: 'leave',      action: 'view',    description: 'View leave requests' },
  { code: 'hrm:leave:request',           module: 'hrm', resource: 'leave',      action: 'request', description: 'Submit leave requests' },
  { code: 'hrm:leave:approve',           module: 'hrm', resource: 'leave',      action: 'approve', description: 'Approve leave requests' },
  { code: 'hrm:payroll:view',            module: 'hrm', resource: 'payroll',    action: 'view',    description: 'View payroll runs' },
  { code: 'hrm:payroll:run',             module: 'hrm', resource: 'payroll',    action: 'run',     description: 'Execute payroll' },
  { code: 'hrm:payslip:view',            module: 'hrm', resource: 'payslip',    action: 'view',    description: 'View own payslips' },
  { code: 'hrm:recruit:view',            module: 'hrm', resource: 'recruit',    action: 'view',    description: 'View job postings and applications' },
  { code: 'hrm:recruit:create',          module: 'hrm', resource: 'recruit',    action: 'create',  description: 'Create job postings' },
  { code: 'hrm:recruit:update',          module: 'hrm', resource: 'recruit',    action: 'update',  description: 'Update applications and interviews' },
  { code: 'hrm:appraisal:view',          module: 'hrm', resource: 'appraisal', action: 'view',    description: 'View all appraisals' },
  { code: 'hrm:appraisal:self',          module: 'hrm', resource: 'appraisal', action: 'self',    description: 'Fill own self-review' },
  { code: 'hrm:appraisal:manage',        module: 'hrm', resource: 'appraisal', action: 'manage',  description: 'Manage appraisal cycles and reviews' },
  // fleet
  { code: 'fleet:vehicle:view',          module: 'fleet', resource: 'vehicle',    action: 'view',    description: 'View vehicles' },
  { code: 'fleet:vehicle:create',        module: 'fleet', resource: 'vehicle',    action: 'create',  description: 'Add vehicles' },
  { code: 'fleet:vehicle:update',        module: 'fleet', resource: 'vehicle',    action: 'update',  description: 'Edit vehicles' },
  { code: 'fleet:driver:view',           module: 'fleet', resource: 'driver',     action: 'view',    description: 'View drivers' },
  { code: 'fleet:driver:create',         module: 'fleet', resource: 'driver',     action: 'create',  description: 'Add drivers' },
  { code: 'fleet:driver:update',         module: 'fleet', resource: 'driver',     action: 'update',  description: 'Edit drivers' },
  { code: 'fleet:trip:view',             module: 'fleet', resource: 'trip',       action: 'view',    description: 'View trips' },
  { code: 'fleet:trip:create',           module: 'fleet', resource: 'trip',       action: 'create',  description: 'Create trips' },
  { code: 'fleet:trip:update',           module: 'fleet', resource: 'trip',       action: 'update',  description: 'Edit trips' },
  { code: 'fleet:fuel:view',             module: 'fleet', resource: 'fuel',       action: 'view',    description: 'View fuel logs' },
  { code: 'fleet:fuel:create',           module: 'fleet', resource: 'fuel',       action: 'create',  description: 'Log fuel entries' },
  { code: 'fleet:compliance:view',       module: 'fleet', resource: 'compliance', action: 'view',    description: 'View compliance documents' },
  { code: 'fleet:compliance:manage',     module: 'fleet', resource: 'compliance', action: 'manage',  description: 'Manage compliance documents' },
  // rm (repair & maintenance)
  { code: 'rm:asset:view',               module: 'rm', resource: 'asset',     action: 'view',    description: 'View assets' },
  { code: 'rm:asset:create',             module: 'rm', resource: 'asset',     action: 'create',  description: 'Register assets' },
  { code: 'rm:asset:update',             module: 'rm', resource: 'asset',     action: 'update',  description: 'Edit assets' },
  { code: 'rm:workorder:view',           module: 'rm', resource: 'workorder', action: 'view',    description: 'View work orders' },
  { code: 'rm:workorder:create',         module: 'rm', resource: 'workorder', action: 'create',  description: 'Create work orders' },
  { code: 'rm:workorder:update',         module: 'rm', resource: 'workorder', action: 'update',  description: 'Update work orders' },
  { code: 'rm:workorder:close',          module: 'rm', resource: 'workorder', action: 'close',   description: 'Close work orders' },
  { code: 'rm:pm:view',                  module: 'rm', resource: 'pm',        action: 'view',    description: 'View PM schedules' },
  { code: 'rm:pm:create',               module: 'rm', resource: 'pm',        action: 'create',  description: 'Create PM schedules' },
  { code: 'rm:pm:update',               module: 'rm', resource: 'pm',        action: 'update',  description: 'Edit PM schedules' },
  { code: 'rm:parts:view',              module: 'rm', resource: 'parts',     action: 'view',    description: 'View spare parts' },
  { code: 'rm:parts:consume',           module: 'rm', resource: 'parts',     action: 'consume', description: 'Log parts consumption' },
] as const;

export type PermissionCode = typeof PERMISSION_CATALOG[number]['code'];

export const SYSTEM_ROLE_NAMES = [
  'Super Admin',
  'Tenant Admin',
  'Accountant',
  'Store Officer',
  'Maintenance Supervisor',
  'Fleet Manager',
  'Sales Rep',
  'HR Manager',
  'Employee (ESS)',
  'Read-Only Auditor',
] as const;

export type SystemRoleName = typeof SYSTEM_ROLE_NAMES[number];
